name: Build and Push image to Docker Hub
on:
    #[workflow_dispatch] provides a button to trigger the workflow instead of running automatically
    push:
        branches:
            - main
        paths:
            - "api/*"
            - "front-end-nextjs/*"
        

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build image
              run: | 
                docker build ./api/ -t aniketpathak028/url-to-qr:latest
                docker build ./front-end-nextjs/ -t aniketpathak028/url-to-qr-frontend:latest
            - name: push image to docker hub
              run: |
                docker login -u aniketpathak028 -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push aniketpathak028/url-to-qr:latest
                docker push aniketpathak028/url-to-qr-frontend:latest
    